// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherFunction.Data;

#nullable disable

namespace WeatherFunction.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310124920_UpdateCityNames")]
    partial class UpdateCityNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeatherFunction.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMainCity")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("NearestMainCityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityName")
                        .IsUnique();

                    b.HasIndex("NearestMainCityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Iasi",
                            IsMainCity = true,
                            Latitude = 47.159999999999997,
                            Longitude = 27.579999999999998
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Suceava",
                            IsMainCity = true,
                            Latitude = 47.630000000000003,
                            Longitude = 26.25
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Bacau",
                            IsMainCity = true,
                            Latitude = 46.57,
                            Longitude = 26.91
                        },
                        new
                        {
                            Id = 4,
                            CityName = "Vaslui",
                            IsMainCity = true,
                            Latitude = 46.640000000000001,
                            Longitude = 27.73
                        },
                        new
                        {
                            Id = 5,
                            CityName = "Roman",
                            IsMainCity = true,
                            Latitude = 46.920000000000002,
                            Longitude = 26.93
                        },
                        new
                        {
                            Id = 6,
                            CityName = "Focsani",
                            IsMainCity = true,
                            Latitude = 45.700000000000003,
                            Longitude = 27.18
                        },
                        new
                        {
                            Id = 7,
                            CityName = "Galati",
                            IsMainCity = true,
                            Latitude = 45.43,
                            Longitude = 28.030000000000001
                        },
                        new
                        {
                            Id = 8,
                            CityName = "Barlad",
                            IsMainCity = true,
                            Latitude = 46.229999999999997,
                            Longitude = 27.670000000000002
                        },
                        new
                        {
                            Id = 9,
                            CityName = "Constanta",
                            IsMainCity = true,
                            Latitude = 44.18,
                            Longitude = 28.649999999999999
                        },
                        new
                        {
                            Id = 10,
                            CityName = "Tulcea",
                            IsMainCity = true,
                            Latitude = 45.18,
                            Longitude = 28.800000000000001
                        },
                        new
                        {
                            Id = 11,
                            CityName = "Braila",
                            IsMainCity = true,
                            Latitude = 45.270000000000003,
                            Longitude = 27.960000000000001
                        },
                        new
                        {
                            Id = 12,
                            CityName = "Buzau",
                            IsMainCity = true,
                            Latitude = 45.149999999999999,
                            Longitude = 26.829999999999998
                        },
                        new
                        {
                            Id = 13,
                            CityName = "Medgidia",
                            IsMainCity = true,
                            Latitude = 44.25,
                            Longitude = 28.27
                        },
                        new
                        {
                            Id = 14,
                            CityName = "Mangalia",
                            IsMainCity = true,
                            Latitude = 43.82,
                            Longitude = 28.579999999999998
                        },
                        new
                        {
                            Id = 15,
                            CityName = "Slobozia",
                            IsMainCity = true,
                            Latitude = 44.560000000000002,
                            Longitude = 27.370000000000001
                        },
                        new
                        {
                            Id = 16,
                            CityName = "Bucharest",
                            IsMainCity = true,
                            Latitude = 44.43,
                            Longitude = 26.100000000000001
                        },
                        new
                        {
                            Id = 17,
                            CityName = "Ploiesti",
                            IsMainCity = true,
                            Latitude = 44.939999999999998,
                            Longitude = 26.02
                        },
                        new
                        {
                            Id = 18,
                            CityName = "Targoviste",
                            IsMainCity = true,
                            Latitude = 44.93,
                            Longitude = 25.449999999999999
                        },
                        new
                        {
                            Id = 19,
                            CityName = "Alexandria",
                            IsMainCity = true,
                            Latitude = 43.969999999999999,
                            Longitude = 25.329999999999998
                        },
                        new
                        {
                            Id = 20,
                            CityName = "Calarasi",
                            IsMainCity = true,
                            Latitude = 44.200000000000003,
                            Longitude = 27.329999999999998
                        },
                        new
                        {
                            Id = 21,
                            CityName = "Craiova",
                            IsMainCity = true,
                            Latitude = 44.32,
                            Longitude = 23.800000000000001
                        },
                        new
                        {
                            Id = 22,
                            CityName = "Pitesti",
                            IsMainCity = true,
                            Latitude = 44.850000000000001,
                            Longitude = 24.870000000000001
                        },
                        new
                        {
                            Id = 23,
                            CityName = "Ramnicu Valcea",
                            IsMainCity = true,
                            Latitude = 45.100000000000001,
                            Longitude = 24.370000000000001
                        },
                        new
                        {
                            Id = 24,
                            CityName = "Targu Jiu",
                            IsMainCity = true,
                            Latitude = 45.039999999999999,
                            Longitude = 23.280000000000001
                        },
                        new
                        {
                            Id = 25,
                            CityName = "Drobeta Turnu Severin",
                            IsMainCity = true,
                            Latitude = 44.630000000000003,
                            Longitude = 22.66
                        },
                        new
                        {
                            Id = 26,
                            CityName = "Timisoara",
                            IsMainCity = true,
                            Latitude = 45.75,
                            Longitude = 21.23
                        },
                        new
                        {
                            Id = 27,
                            CityName = "Arad",
                            IsMainCity = true,
                            Latitude = 46.18,
                            Longitude = 21.309999999999999
                        },
                        new
                        {
                            Id = 28,
                            CityName = "Oradea",
                            IsMainCity = true,
                            Latitude = 47.07,
                            Longitude = 21.920000000000002
                        },
                        new
                        {
                            Id = 29,
                            CityName = "Deva",
                            IsMainCity = true,
                            Latitude = 45.880000000000003,
                            Longitude = 22.91
                        },
                        new
                        {
                            Id = 30,
                            CityName = "Cluj",
                            IsMainCity = true,
                            Latitude = 46.770000000000003,
                            Longitude = 23.59
                        },
                        new
                        {
                            Id = 31,
                            CityName = "Baia Mare",
                            IsMainCity = true,
                            Latitude = 47.659999999999997,
                            Longitude = 23.579999999999998
                        },
                        new
                        {
                            Id = 32,
                            CityName = "Satu Mare",
                            IsMainCity = true,
                            Latitude = 47.789999999999999,
                            Longitude = 22.879999999999999
                        },
                        new
                        {
                            Id = 33,
                            CityName = "Zalau",
                            IsMainCity = true,
                            Latitude = 47.189999999999998,
                            Longitude = 23.059999999999999
                        },
                        new
                        {
                            Id = 34,
                            CityName = "Bistrita",
                            IsMainCity = true,
                            Latitude = 47.130000000000003,
                            Longitude = 24.5
                        },
                        new
                        {
                            Id = 35,
                            CityName = "Brasov",
                            IsMainCity = true,
                            Latitude = 45.649999999999999,
                            Longitude = 25.609999999999999
                        },
                        new
                        {
                            Id = 36,
                            CityName = "Sibiu",
                            IsMainCity = true,
                            Latitude = 45.799999999999997,
                            Longitude = 24.149999999999999
                        },
                        new
                        {
                            Id = 37,
                            CityName = "Targu Mures",
                            IsMainCity = true,
                            Latitude = 46.539999999999999,
                            Longitude = 24.559999999999999
                        },
                        new
                        {
                            Id = 38,
                            CityName = "Alba Iulia",
                            IsMainCity = true,
                            Latitude = 46.07,
                            Longitude = 23.579999999999998
                        },
                        new
                        {
                            Id = 39,
                            CityName = "Sfantu Gheorghe",
                            IsMainCity = true,
                            Latitude = 45.859999999999999,
                            Longitude = 25.789999999999999
                        },
                        new
                        {
                            Id = 40,
                            CityName = "Miercurea Ciuc",
                            IsMainCity = true,
                            Latitude = 46.359999999999999,
                            Longitude = 25.800000000000001
                        },
                        new
                        {
                            Id = 41,
                            CityName = "Sinaia",
                            IsMainCity = true,
                            Latitude = 45.350000000000001,
                            Longitude = 25.550000000000001
                        });
                });

            modelBuilder.Entity("WeatherFunction.Models.SearchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("SearchHistories");
                });

            modelBuilder.Entity("WeatherFunction.Models.WeatherCurrent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeatherData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.ToTable("WeatherCurrents");
                });

            modelBuilder.Entity("WeatherFunction.Models.WeatherHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeatherData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("WeatherHistories");
                });

            modelBuilder.Entity("WeatherFunction.Models.City", b =>
                {
                    b.HasOne("WeatherFunction.Models.City", "NearestMainCity")
                        .WithMany()
                        .HasForeignKey("NearestMainCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NearestMainCity");
                });

            modelBuilder.Entity("WeatherFunction.Models.SearchHistory", b =>
                {
                    b.HasOne("WeatherFunction.Models.City", "City")
                        .WithMany("SearchHistories")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WeatherFunction.Models.WeatherCurrent", b =>
                {
                    b.HasOne("WeatherFunction.Models.City", "City")
                        .WithMany("WeatherCurrents")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WeatherFunction.Models.WeatherHistory", b =>
                {
                    b.HasOne("WeatherFunction.Models.City", "City")
                        .WithMany("WeatherHistories")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WeatherFunction.Models.City", b =>
                {
                    b.Navigation("SearchHistories");

                    b.Navigation("WeatherCurrents");

                    b.Navigation("WeatherHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
